version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: youp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - youp_new_data:/var/lib/postgres
volumes:
  youp_new_data:
